language: haskell
dist: xenial

cache:
  directories:
    - $HOME/.cabal/package
    - $HOME/.cabal/store

cabal: "2.4"

matrix:
  fast_finish: true
  include:
    - env: BUILD=cabal
      ghc: "8.8.3"

    - env: BUILD=cabal
      ghc: "8.6.5"

    - env: BUILD=cabal
      ghc: "8.4.4"

    - env: BUILD=cabal
      ghc: "8.2.2"
